# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceed40bbb545dc5813b97b917439e2f1975ab925854ab100d479ee969639b658195eb08778100bc77d3d670f9951557842dd9ccc44aba690fc957fe81ea3d1bb

test:
  secret_key_base: 37900a771b0c90853523555e443104b2e6fbc0ed15fe5286931b9ede1a1e62f1af052b5afee0ebb25ad684e75efdbb2695b96536b6985d92dd3d36c26d2f57e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
